# Generated by Django 4.2.2 on 2023-08-22 09:17

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerId', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContestTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(blank=True)),
                ('endTime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionId', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('questionNumber', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('ipFormate', tinymce.models.HTMLField()),
                ('opFormate', tinymce.models.HTMLField()),
                ('constraints', tinymce.models.HTMLField(null=True)),
                ('inputOutputBlock', tinymce.models.HTMLField(null=True)),
                ('sampleIp', models.TextField(blank=True, null=True)),
                ('sampleOp', models.TextField(blank=True, null=True)),
                ('difficultyLevel', models.IntegerField(default=0)),
                ('maxPoints', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('timeLimit', models.IntegerField(default=1)),
                ('memoryLimit', models.IntegerField(default=524288)),
                ('accuracy', models.IntegerField(default=0)),
                ('totalSubmissions', models.IntegerField(default=0)),
                ('author', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('junior', 'junior'), ('senior', 'senior'), ('both', 'both')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcaseNumber', models.IntegerField()),
                ('inputFile', models.FileField(blank=True, upload_to=core.models.getIpPath, verbose_name='Testcase Input')),
                ('outputFile', models.FileField(blank=True, upload_to=core.models.getOpPath, verbose_name='Testcase Output')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('isLogin', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('isJunior', models.BooleanField(default=True)),
                ('lastUpdate', models.DateTimeField(default=datetime.datetime(2023, 8, 22, 14, 47, 51, 727777))),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'python'), ('cpp', 'cpp'), ('c', 'c')], max_length=10)),
                ('code', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('attemptedNumber', models.IntegerField(default=0)),
                ('submissionTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('WA', 'Wrong Answer'), ('AC', 'Accepted'), ('PEN', 'Pending')], max_length=5, null=True)),
                ('isCorrect', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('feedBack', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
