# Generated by Django 4.2.2 on 2023-07-21 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_container_alter_team_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 21, 37, 23, 788933)),
        ),
    ]
