# Generated by Django 4.2.2 on 2023-06-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_team_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='setter',
            field=models.CharField(default='', max_length=100),
        ),
    ]
