# Generated by Django 4.2.2 on 2023-06-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_question_setter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python', 'python'), ('cpp', 'cpp'), ('c', 'c')], max_length=10),
        ),
    ]
