# Generated by Django 4.2.2 on 2023-06-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_submission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attemptedNumber',
            field=models.IntegerField(default=0),
        ),
    ]
