# Generated by Django 4.2.2 on 2023-08-22 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_question_inputoutputblock_alter_question_constraints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 13, 31, 7, 231414)),
        ),
    ]
